//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProektsBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public string Text { get; set; }
        public int IdType { get; set; }
        public int IdUsers { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual TypeOrder TypeOrder { get; set; }
        public virtual Users Users { get; set; }
    }
}
